"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { useLessonPlans } from "@/hooks/useLessonPlans";
import { useSchoolDateNavigation } from "@/hooks/useSchoolDateNavigation";
import { useSchedule } from "@/hooks/useSchedule";
import {
  buildScheduleDraftsForDate,
  hasTemplateForDate as hasWeeklyTemplateForDate,
  loadWeeklyTemplate,
  PublishMode,
  WeeklyTemplate
} from "@/lib/weeklyTemplate";
import {
  createScheduleItem,
  deleteScheduleItem,
  listScheduleByDate,
  ScheduleItem,
  ScheduleStatus,
  updateScheduleItem
} from "@/lib/schedule";

export type DashboardMode = "today" | "template";

export type PreviewDateItem = {
  date: string;
  label: string;
  count: number;
  hasTemplate: boolean;
};

type GenerateResult = {
  created: number;
  skipped: number;
  hasTemplate: boolean;
};

export type UseDashboardStateResult = {
  mode: DashboardMode;
  setMode: (mode: DashboardMode) => void;
  date: string;
  setDate: (dateIso: string) => void;
  goPrevSchoolDay: () => void;
  goNextSchoolDay: () => void;
  isWeekendDate: boolean;
  isTodaySelected: boolean;
  previewItems: PreviewDateItem[];
  lessonPlans: { id: string; title: string }[];
  items: ScheduleItem[];
  allItems: ScheduleItem[];
  struggledCount: number;
  nextClass: ScheduleItem | null;
  highlightedItemId: string | null;
  templateNotice: string | null;
  updateStatus: (id: string, status: ScheduleStatus) => void;
  updateNotes: (id: string, notes: string) => void;
  deleteItem: (id: string) => void;
  jumpToNextUp: () => void;
  generateDayFromTemplate: (dateIso: string, mode?: PublishMode, template?: WeeklyTemplate) => GenerateResult;
  loading: boolean;
  error: string | null;
  hasTemplateForDate: (dateIso: string, template?: WeeklyTemplate) => boolean;
};

function nowMinutes(): number {
  const now = new Date();
  return now.getHours() * 60 + now.getMinutes();
}

function itemStartMinutes(item: ScheduleItem): number {
  const [hoursRaw, minutesRaw] = item.startTime.split(":");
  const hours = Number(hoursRaw);
  const minutes = Number(minutesRaw);
  return (Number.isNaN(hours) ? 0 : hours) * 60 + (Number.isNaN(minutes) ? 0 : minutes);
}

function toDateLabel(dateIso: string): string {
  const parsed = new Date(`${dateIso}T00:00:00`);
  const weekday = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][parsed.getDay()] ?? "";
  return `${weekday} ${parsed.getMonth() + 1}/${parsed.getDate()}`;
}

export function useDashboardState(): UseDashboardStateResult {
  const [mode, setMode] = useState<DashboardMode>("today");
  const [templateNotice, setTemplateNotice] = useState<string | null>(null);
  const [highlightedItemId, setHighlightedItemId] = useState<string | null>(null);
  const autoGeneratedDatesRef = useRef<Record<string, boolean>>({});
  const noticeTimerRef = useRef<number | null>(null);

  const dateNavigation = useSchoolDateNavigation();
  const { date, todayIso, setDate, goPrevSchoolDay, goNextSchoolDay, previewDates, isWeekendDate } = dateNavigation;
  const schedule = useSchedule(date);
  const { itemsForDate, allItems, refreshAll, isLoading: scheduleLoading, error: scheduleError } = schedule;
  const lessons = useLessonPlans();
  const { lessonPlans, isLoading: lessonPlansLoading, error: lessonPlansError } = lessons;

  const showTemplateNotice = useCallback(() => {
    setTemplateNotice("Generated from weekly template.");

    if (noticeTimerRef.current) {
      window.clearTimeout(noticeTimerRef.current);
    }

    noticeTimerRef.current = window.setTimeout(() => {
      setTemplateNotice(null);
      noticeTimerRef.current = null;
    }, 4000);
  }, []);

  const generateDayFromTemplate = useCallback(
    (targetDateIso: string, publishMode: PublishMode = "fill-empty-only", template?: WeeklyTemplate): GenerateResult => {
      const sourceTemplate = template ?? loadWeeklyTemplate();
      const hasTemplate = hasWeeklyTemplateForDate(targetDateIso, sourceTemplate);
      if (!hasTemplate) return { created: 0, skipped: 0, hasTemplate: false };

      if (publishMode === "overwrite") {
        for (const existing of listScheduleByDate(targetDateIso)) {
          deleteScheduleItem(existing.id);
        }
      }

      const drafts = buildScheduleDraftsForDate(targetDateIso, sourceTemplate);
      const existingSlotKeys = new Set(
        listScheduleByDate(targetDateIso).map((item) => `${item.startTime}|${item.endTime}`)
      );

      let created = 0;
      let skipped = 0;

      for (const draft of drafts) {
        const slotKey = `${draft.startTime}|${draft.endTime}`;
        const slotTaken = existingSlotKeys.has(slotKey);

        if (publishMode === "fill-empty-only" && slotTaken) {
          skipped += 1;
          continue;
        }

        createScheduleItem({
          date: targetDateIso,
          classLabel: draft.classLabel,
          grade: draft.grade,
          topic: draft.topic,
          startTime: draft.startTime,
          endTime: draft.endTime,
          lessonPlanId: draft.lessonPlanId
        });

        existingSlotKeys.add(slotKey);
        created += 1;
      }

      refreshAll({ force: true });
      return { created, skipped, hasTemplate: true };
    },
    [refreshAll]
  );

  useEffect(() => {
    if (mode !== "today") return;
    if (isWeekendDate) return;
    if (autoGeneratedDatesRef.current[date]) return;

    if (itemsForDate.length > 0) {
      autoGeneratedDatesRef.current[date] = true;
      return;
    }

    const result = generateDayFromTemplate(date, "fill-empty-only");
    if (result.hasTemplate) {
      autoGeneratedDatesRef.current[date] = true;
    }
    if (result.created > 0) {
      showTemplateNotice();
    }
  }, [date, generateDayFromTemplate, isWeekendDate, itemsForDate.length, mode, showTemplateNotice]);

  useEffect(() => {
    return () => {
      if (noticeTimerRef.current) {
        window.clearTimeout(noticeTimerRef.current);
      }
    };
  }, []);

  const previewItems = useMemo<PreviewDateItem[]>(() => {
    const countByDate = new Map<string, number>();

    for (const item of allItems) {
      countByDate.set(item.date, (countByDate.get(item.date) ?? 0) + 1);
    }

    return previewDates.map((previewDate) => {
      const count = countByDate.get(previewDate) ?? 0;
      return {
        date: previewDate,
        label: toDateLabel(previewDate),
        count,
        hasTemplate: count === 0 ? hasWeeklyTemplateForDate(previewDate) : false
      };
    });
  }, [allItems, previewDates]);

  const struggledCount = useMemo(
    () => itemsForDate.filter((item) => item.status === "struggled").length,
    [itemsForDate]
  );

  const nextClass = useMemo(() => {
    const now = nowMinutes();
    return itemsForDate.find((item) => itemStartMinutes(item) >= now) ?? null;
  }, [itemsForDate]);

  const isTodaySelected = date === todayIso;

  const updateStatus = useCallback(
    (id: string, status: ScheduleStatus) => {
      updateScheduleItem(id, { status });
      refreshAll({ force: true });
    },
    [refreshAll]
  );

  const updateNotes = useCallback(
    (id: string, notes: string) => {
      updateScheduleItem(id, { struggleNotes: notes });
      refreshAll({ force: true });
    },
    [refreshAll]
  );

  const deleteItem = useCallback(
    (id: string) => {
      deleteScheduleItem(id);
      refreshAll({ force: true });
    },
    [refreshAll]
  );

  const jumpToNextUp = useCallback(() => {
    if (!nextClass) return;

    const target = document.getElementById(`timeline-item-${nextClass.id}`);
    target?.scrollIntoView({ behavior: "smooth", block: "center" });

    setHighlightedItemId(nextClass.id);
    window.setTimeout(() => {
      setHighlightedItemId((current) => (current === nextClass.id ? null : current));
    }, 1800);
  }, [nextClass]);

  return {
    mode,
    setMode,
    date,
    setDate,
    goPrevSchoolDay,
    goNextSchoolDay,
    isWeekendDate,
    isTodaySelected,
    previewItems,
    lessonPlans,
    items: itemsForDate,
    allItems,
    struggledCount,
    nextClass,
    highlightedItemId,
    templateNotice,
    updateStatus,
    updateNotes,
    deleteItem,
    jumpToNextUp,
    generateDayFromTemplate,
    loading: scheduleLoading || lessonPlansLoading,
    error: scheduleError ?? lessonPlansError,
    hasTemplateForDate: hasWeeklyTemplateForDate
  };
}
